### ISSUE TITLE
The heading on the "Create Course" page displays as "Create Workshop"

### ISSUE THREAD

**Issue by nunju9a** [treehouse-apprenticeship/athena_nj_team1#1]
Issue Description
Need to update the "Create Course" page header to display "Create Course" instead of "Create Workshop".

Steps to Reproduce

Using the React client, click on the "Sign In" link displayed in the header to browse to the "Sign In" page.
Sign in using Joe's user information.
Email Address: joe@smith.com
Password: joepassword
From the Course List page (i.e. the "Home" page), click on the "New Course" card to browse to the Create Course page.
Notice that the page heading displays as "Create Workshop".
The page heading should display as "Create Course".

@martyv4

**Comment by martyv4** [comment]
will do @nunju9a

**Comment by nunju9a** [comment]
Good job @martyv4 and @sanma1i
