### ISSUE TITLE
Creating a new course returns an unexpected HTTP status code

### ISSUE THREAD

**Issue by nunju9a** [treehouse-apprenticeship/athena_nj_team1#3]
Issue Description
Creating a new course returns a 202 Accepted HTTP status code instead of the expected 201 Created HTTP status code. As described in bug #2, creating a new user is currently broken, so it's not possible to determine if the REST API is returning the correct HTTP status code when creating a new user.

When creating a new course from the React client, the "Error" page will be displayed because of the unexpected HTTP status code. Using Postman to test the REST API will allow you to see easily see what HTTP status code is being returned from the server.

Steps to Reproduce

Using Postman, send a POST request to the REST API.
URL: http://localhost:5000/api/courses
Basic Auth Authorization Header: Username=joe@smith.com, Password=joepassword
Body (as JSON):
{
    "title": "Another New Course",
    "description": "My course description",
    "user": "57029ed4795118be119cc437"
}
The REST API returns a response with a 202 Accepted HTTP status code.
The REST API should return a response with a 201 Created HTTP status code.

@martyv4

**Comment by martyv4** [comment]
**

> will do

** @nunju9a

**Comment by nunju9a** [comment]
good job @martyv4  @sanma1i
